name: heather_components
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: ntaoo <ntaoo.g@gmail.com>
homepage: https://github.com/ntaoo/heather_components

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  angular2:
  angular2_components:

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

transformers:
  - angular2